// This file statically imports all game icon images so they can be bundled correctly.
// A static object is used to map a game's name to its image path.

// NOTE: You will need to replace this placeholder with your actual assets.
export const gameIcons = {
  '0': require('./game-icons/0.webp'),
  '1': require('./game-icons/1.webp'),
  '2': require('./game-icons/2.webp'),
  '3': require('./game-icons/3.webp'),
  '4': require('./game-icons/4.webp'),
  '5': require('./game-icons/5.webp'),
  '6': require('./game-icons/6.webp'),
  '7': require('./game-icons/7.webp'),
  '8': require('./game-icons/8.webp'),
  '9': require('./game-icons/9.webp'),
  'a': require('./game-icons/a.webp'),
  'b': require('./game-icons/b.webp'),
  'c': require('./game-icons/c.webp'),
  'd': require('./game-icons/d.webp'),
  'e': require('./game-icons/e.webp'),
  'f': require('./game-icons/f.webp'),
  'g': require('./game-icons/g.webp'),
  'h': require('./game-icons/h.webp'),
  'i': require('./game-icons/i.webp'),
  'j': require('./game-icons/j.webp'),
  'k': require('./game-icons/k.webp'),
  'l': require('./game-icons/l.webp'),
  'm': require('./game-icons/m.webp'),
  'n': require('./game-icons/n.webp'),
  'o': require('./game-icons/o.webp'),
  'p': require('./game-icons/p.webp'),
  'q': require('./game-icons/q.webp'),
  'r': require('./game-icons/r.webp'),
  's': require('./game-icons/s.webp'),
  't': require('./game-icons/t.webp'),
  'u': require('./game-icons/u.webp'),
  'v': require('./game-icons/v.webp'),
  'w': require('./game-icons/w.webp'),
};